/* MTI_DPI */

/*
 * Copyright 2002-2010 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux'
 */
#ifndef INCLUDED_CNT7
#define INCLUDED_CNT7

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
void
counter7(
    void* inst,
    svBitVecVal* out,
    const svBitVecVal* in,
    svBit reset,
    svBit load);

DPI_LINK_DECL DPI_DLLESPEC
void*
counter7_new();

#endif 
